- name: Installing Python MySQL connector
  yum: name=http://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-connector-python-1.2.1-1.el6.noarch.rpm

- name: Installing Java MySQL connector
  get_url: url=http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.30.tar.gz dest=/home/vagrant/

- name: Installing OpenJDK
  yum: name=java-1.7.0-openjdk-devel
