- shell: ifconfig |grep 192.168.70|sed 's/.*addr://g'|sed 's/  Bcast.*//g'|tr -d '.' | cut -c 6-
  register: server_id

- set_fact: port="3306"
- set_fact: socket="/var/lib/mysql/mysql.sock"
- set_fact: pidf="/var/run/mysqld/mysqld.pid"
- set_fact: errorl="/var/log/mysqld.log"
- set_fact: datadir="/var/lib/mysql"
  
- name: Adding the /etc/my.cnf file.
  template: src=etc/my.cnf.t dest=/etc/my.cnf


- shell: /etc/init.d/mysql restart