- name: Adding fabic mysql users
  shell: /usr/bin/mysql -S/var/lib/mysql/mysql.sock -uroot -e "grant SUPER on *.* to fabric@'%'"

- name: Adding fabic mysql users
  shell: /usr/bin/mysql -S/var/lib/mysql/mysql.sock -uroot -e "grant ALL on *.* to fabric@'%'"

# and now the same for the second instance
- name: (mysqld2) Adding fabic mysql users
  shell: /usr/bin/mysql -S/var/lib/mysql2/mysql2.sock -uroot -e "grant SUPER on *.* to fabric@'%'"

- name: (mysqld2) Adding fabic mysql users
  shell: /usr/bin/mysql -S/var/lib/mysql2/mysql2.sock -uroot -e "grant ALL on *.* to fabric@'%'" 

