- name: copying fabric.cfg
  template: dest=/etc/mysql/fabric.cfg src=etc/mysql/fabric.cfg 

- name: initializing fabric if needed
  shell: /usr/bin/mysqlfabric manage setup
  args: 
     creates: /var/lib/mysql/fabric/

- name: start fabric if needed
  shell: /usr/bin/mysqlfabric manage start --daemon &>/dev/null
