#- include: tasks/fabric-mysql-user.yml

- hosts: all
  sudo: yes 
  tasks:
      - include: tasks/common.yml
      - include: tasks/epel-repository.yml
      - include: tasks/mysql-repository.yml
      - include: tasks/mysql-56-server.yml
      - include: tasks/fabric-packages.yml
      - include: tasks/fabric-store-config.yml
      - include: tasks/fabric-store-mysql-user.yml
